independent configuration files for commands

diff --git a/Packages/server/apache/bin/balancer b/Packages/server/apache/bin/balancer
--- a/Packages/server/apache/bin/balancer
+++ b/Packages/server/apache/bin/balancer
@@ -19,23 +19,35 @@ show_help() {
     -h | --http-port: http listen port on publish ip, default to 80
     -s | --ssl-port : ssl listen port on publish ip, default to 443 
 commands:
-    start   : if not started, start node balancer
-    stop    : stop running balancer server
-    reload  : reload balancer server,
-              useful to reaload after fetching ssl certificate
-    nodeadd : add a backend node
-        commandargs: ip:port
-    noderm  : remove a backend node
-        commandargs: ip:port
-    routeadd: Not implemented, add a routed node
-        commandargs: routeid ip:port
-    routedel: Not implemented, remove a routed node
-        commandargs: routeid ip:port
-    *       : custom command to run in balancer server, if not already
-              running, this command will create an instance to run the command
-        commandargs: see man page of command.
+    start           : if not started, start node balancer
+    stop            : stop running balancer server
+    reload          : reload balancer server,
+                        useful to reaload after fetching ssl certificate
+    nodeadd         : add a backend node
+        commandargs     : ip:port
+    noderm          : remove a backend node
+        commandargs     : ip:port
+    routeadd        : Add routing to route_aliases domain
+        commandargs     : domain ip:port [...ip:port]
+    routedel        : Remove route for domain in route_aliases
+        commandargs     : domain ip:port [...ip:port]
+    routeempty      : clear all routes for a domain in route_aliases
+    *               : custom command to run in balancer server, if not already
+                        running, this command will create an instance to run the command
+        commandargs     : see man page of command.
     "
 }
+
+[[ ! -f "${DIR}/balancer.conf" ]] && >&2 echo "node balancer configuration file not found" && exit 1
+# include default values
+source "$(dirname "$(dirname "${BASH_SOURCE[0]}")")/balancer.conf"
+source "${DIR}/balancer.conf"
+
+#removing commandline only arguments
+unset publishIp
+unset http_port
+unset ssl_port
+unset move
 
 args=()
 nodes=()
@@ -99,7 +111,6 @@ exists=$(docker ps -f 'name=^'"${BALANCER_CONTAINER}"'$' -q)
 
 if [[ -z "${exists}" ]]; then
 
-
     # get exposed port
     if [[ -z "${BALANCER_LISTEN_PORT}" ]]; then
         BALANCER_LISTEN_PORT=$(dockerinfo variable "${BALANCER_IMAGE}" LISTEN_PORT)
@@ -123,12 +134,14 @@ if [[ -z "${exists}" ]]; then
         if [[ "${BALANCER_SSL_ONLY:-0}" != "0" ]]; then
             export DOCKER_OPTION_ssl_only="-e=SSL_ONLY=1"
         fi
+
         if [[ -n "${BALANCER_CONFIG_PATH}" ]]; then
             if [[ ! -d "${BALANCER_CONFIG_PATH}" ]]; then
                 mkdir -p "${BALANCER_CONFIG_PATH}"
             fi
             export SITE_PATH_md_dir=type=bind,source=${BALANCER_CONFIG_PATH},destination=/etc/apache2/md
         fi
+
         if [[ -n "${BALANCER_CERTIFICATE_PATH}" ]]; then
             if [[ ! -d "${BALANCER_CERTIFICATE_PATH}" ]]; then
                 mkdir -p "${BALANCER_CERTIFICATE_PATH}"
@@ -158,6 +171,10 @@ if [[ -z "${exists}" ]]; then
             mkdir -p "${BALANCER_LOG_PATH}"
         fi
     fi
+
+    if [[ -n "${ALIAS_ROUTES}" ]]; then
+        export "DOCKER_OPTION_alias_route=-e=ALIAS_ROUTES=${ALIAS_ROUTES}"
+    fi
 fi
 
 case "$1" in
@@ -167,7 +184,7 @@ case "$1" in
             cmd "${BALANCER_CONTAINER}" "${BALANCER_IMAGE}" -d -e CONFIG_TYPE=balancer --  -- "${start}"
             while [[ $? -eq 0 ]]; do
                 sleep 1
-                docker exec "${BALANCER_CONTAINER}" bash -c '[[ -f /etc/apache2/sites-enabled/default.conf ]] && exit 1 || exit 0 '
+                docker exec "${BALANCER_CONTAINER}" bash -c '[[ -f /etc/apache2/sites-enabled/00_default.conf ]] && exit 1 || exit 0 '
             done
             for node in "${nodes[@]}"; do
                 cmd "${BALANCER_CONTAINER}" "${BALANCER_IMAGE}" childBalancer.sh add "${node}"
@@ -193,6 +210,22 @@ case "$1" in
             exit;
         fi
         docker exec "${BALANCER_CONTAINER}" childBalancer.sh remove "${2}"
+        ;;
+    routeadd)
+        [[ $# -lt 3 ]] && >&2 echo "Usage: routeadd domain ip:port" && exit 1
+        [[ -z "${exists}" ]] && >&2 echo "Container not running" && exit 1
+        [[ " ${ALIAS_ROUTES} " != *" $2 "* ]] && >&2 echo "domain $2 is not in ALIAS_ROUTES ${ALIAS_ROUTES}" && exit 1
+        docker exec "${BALANCER_CONTAINER}" siteBalancer.sh "$2" add "${@:3}"
+        ;;
+    routedel)
+        [[ $# -lt 3 ]] && >&2 echo "Usage: routeadd domain ip:port" && exit 1
+        [[ -z "${exists}" ]] && >&2 echo "Container not running" && exit 1
+        [[ "${ALIAS_ROUTES}" != *" $2 "* ]] && >&2 echo "domain is not in ALIAS_ROUTES" && exit 1
+        docker exec "${BALANCER_CONTAINER}" siteBalancer.sh "$2" remove "${@:3}"
+        ;;
+    routeclear)
+        [[ -z "${exists}" ]] && >&2 echo "Container not running" && exit 1
+        docker exec "${BALANCER_CONTAINER}" siteBalancer.sh "$2" empty
         ;;
     env)
         env
diff --git a/Packages/server/apache/bin/web b/Packages/server/apache/bin/web
--- a/Packages/server/apache/bin/web
+++ b/Packages/server/apache/bin/web
@@ -31,6 +31,16 @@ command:
     "
 }
 
+[[ ! -f "${DIR}/web.conf" ]] && >&2 echo "web server configuration file not found" && exit 1
+# include default values
+source "$(dirname "$(dirname "${BASH_SOURCE[0]}")")/web.conf"
+source "${DIR}/web.conf"
+
+unset publishIp
+unset http_port
+unset trust
+unset move
+
 args=()
 nodes=()
 while [[ $# -gt 0 ]]; do
@@ -80,6 +90,7 @@ DOCUMENT_ROOT="${DOCUMENT_ROOT:-"/home/www"}"
 WEB_LOG_LEVEL="${WEB_LOG_LEVEL:-"warn"}"
 WEB_LOG_PATH="${WEB_LOG_PATH:-"${DATA}/Webserver"}"
 WEB_REPO_BRANCH="${WEB_REPO_BRANCH:-"development"}"
+APP_PRIVATE_ROOT="${APP_PRIVATE_ROOT:-"${ASSET}/www"}"
 
 start="$(dockerinfo startup_command "${WEB_IMAGE}")"
 mapfile -t exists<<<"$(docker ps -f 'name=^'"${WEB_CONTAINER}"'\d*$' -q)"
@@ -116,11 +127,12 @@ if [[ (${#exists[@]} -eq 0) || ("${1}" = "start") ]]; then
         export DOCKER_OPTION_site_log_level="-e=SITE_LOG_LEVEL=${WEB_LOG_LEVEL}"
     fi
     # mounting assets as readonly
-    if [[ (-n ${APP_PRIVATE_ROOT}) && (-n ${DOCUMENT_ROOT}) ]]; then
+    if [[ -n ${DOCUMENT_ROOT} ]]; then
         dirs=(${WEB_DOCUMENT_ASSETS})
         for dir in "${dirs[@]}"; do
             # Mounting APP_PRIVATE_ROOT/DIR TO DOCUMENT_ROOT/DIR
-            export "SITE_PATH_$dir=type=bind,source='${APP_PRIVATE_ROOT%/}/${dir}',destination='${DOCUMENT_ROOT%/}/${dir}',readonly"
+            name="$(sed 's/[^a-zA-Z0-9_]/_/g' <<<"${dir}")"
+            export "SITE_PATH_$name=type=bind,source=${APP_PRIVATE_ROOT%/}/${dir},destination=${DOCUMENT_ROOT%/}/${dir},readonly"
         done
     fi
 
@@ -156,7 +168,7 @@ case "$1" in
         cmd "${container}" "${WEB_IMAGE}" -d --  -- "${start}"
         while [[ $? -eq 0 ]]; do
             sleep 1
-            docker exec "${container}" bash -c '[[ -f /etc/apache2/sites-enabled/default.conf ]] && exit 1 || exit 0 '
+            docker exec "${container}" bash -c '[[ -f /etc/apache2/sites-enabled/00_default.conf ]] && exit 1 || exit 0 '
         done
         for node in "${nodes[@]}"; do
             docker exec "${container}" appBalancer.sh add "${node}"
diff --git a/Packages/server/application/bin/app b/Packages/server/application/bin/app
--- a/Packages/server/application/bin/app
+++ b/Packages/server/application/bin/app
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+set -ae
 # application server
 # Usage: $0 start [dbip] [ip:port] | stop
 #              dbip : ip address of database server, a domain "dbhost"
@@ -20,17 +21,35 @@ show_help() {
     -p | --port         : published port
     -n | --dns          : dns server
     -m | --mail         : mail server
+    --id                : id of container app, a natural number,
+                          if not specified,
+                            default to largest running container id.
+                            or minimum possible id in case of start command.
 Commands:
     start               : start new application server
-    stop                : stop an application server
+    stop                : stop an application server specified by --id,
     stopall             : stop all instance of application server
-    url [id]            : get ip address of application server
+    url                 : get ip address of application server specified by --id
     update              : update application source
     hostadd domain ip   : add hosts file entry for all application server
     hostrm domain ip    : remove hosts file entry from all application server
-    [id=0] *            : execute custom command in application server.
+    *                   : execute custom command in application server, server is choosem by --id parameter.
     "
 }
+
+[[ ! -f "${DIR}/app.conf" ]] && >&2 echo "application configuration file not found" && exit 1
+# include default values
+source "$(dirname "$(dirname "${BASH_SOURCE[0]}")")/app.conf"
+source "${DIR}/app.conf"
+
+unset publishIp
+unset http_port
+unset dns
+unset mail
+unset db
+unset move
+unset CID
+
 args=()
 while [[ $# -gt 0 ]]; do
     case $1 in
@@ -52,6 +71,14 @@ while [[ $# -gt 0 ]]; do
             ;;
         --db|-d)
             db="$2"
+            shift
+            ;;
+        --id)
+            if [[ "$2" =~ '^[0-9]+$' ]]; then
+                CID="$2"
+            else
+                >&2 echo "option --id needs to be positive integer" && exit 1
+            fi
             shift
             ;;
         start|stop|stopall|update|url|hostadd|hostrm)
@@ -90,10 +117,34 @@ DOCUMENT_ROOT="${DOCUMENT_ROOT:-"/home/www"}"
 APP_WRITE_MOUNT="${APP_WRITE_MOUNT:-1}"
 
 start="$(dockerinfo startup_command "${APP_IMAGE}")"
-mapfile -t exists <<< "$(docker ps -f 'name=^'"${APP_CONTAINER}"'\d*$' -q)"
+mapfile -t exists <<< "$(docker ps -f 'name=^'"${APP_CONTAINER}${CID:-\d*}"'$' --format '{{.Names}}')"
 
 if [[ (${#exists[@]} -eq 1) && (-z "${exists[0]}") ]]; then
     exists=()
+fi
+if [[ -z "${CID}" ]]; then
+    MAX_ID=0;
+    for cname in "${exists[@]}"; do
+        id=${cname#${APP_CONTAINER}}
+        ids+=("${id}")
+        if [[ ${id} -gt ${MAX_ID} ]]; then
+            MAX_ID=${id}
+        fi
+    done
+    if [[ ${#ids[@]} -eq $((MAX_ID + 1)) ]]; then
+        NEXT_ID=$((MAX_ID + 1))
+    else
+        NEXT_ID=0
+        while [[ ${NEXT_ID} -le ${MAX_ID} ]]; do
+            if [[ " ${MAX_ID[*]} "] != *" ${NEXT_ID} "* ]]; then
+                break;
+            fi
+            ((NEXT_ID ++))
+        done
+    fi
+else
+    MAX_ID=${CID}
+    NEXT_ID=${CID}
 fi
 
 if [[ -z "${APP_LISTEN_PORT}" ]]; then
@@ -102,9 +153,8 @@ else
     export DOCKER_OPTION_listen_port="-e=LISTEN_PORT=${APP_LISTEN_PORT}"
 fi
 
-if [[ ("${#exists[@]}" -eq 0) || ("${1}" = "start") ]]; then
+initialize_container() {
     # mount document root.
-
     [[ -n "${mail}" ]] && export DOCKER_OPTION_mailer="-e=MAIL_FORWARD_HOST=${mail}"
     [[ -n "${dns}" ]] && export DOCKER_OPTION_dns="-e=DNS_SERVER=${dns}"
 
@@ -183,25 +233,47 @@ if [[ ("${#exists[@]}" -eq 0) || ("${1}" = "start") ]]; then
     if [[ -n "${publishIp}" ]]; then
         export "DOCKER_OPTION_publish_port=--publish=${publishIp}:${port}:${APP_LISTEN_PORT}"
     fi
-fi
+}
 
 case "$1" in
     start)
         # get arguments for db, mail and dns
-
-        cmd "${APP_CONTAINER}${#exists[@]}" "${APP_IMAGE}" -d -w "${DOCUMENT_ROOT}" --  -- "${start}"
-        test -n "${db}" && cmd "${APP_CONTAINER}${#exists[@]}" "${APP_IMAGE}" host.sh add "dbhost" "${db}"
+        if [[ (-n ${CID})  && (${#exists[@]} -ne 0) ]]; then
+            >&2 echo "container already running"
+            exit 1
+        fi
+        initialize_container
+        if cmd "${APP_CONTAINER}${NEXT_ID}" "${APP_IMAGE}" -d -w "${DOCUMENT_ROOT}" --  -- "${start}"; then
+            if [[ -n "${db}" ]]; then
+                docker exec "${APP_CONTAINER}${NEXT_ID}" host.sh add "dbhost" "${db}"
+            fi
+        else
+            exit 1
+        fi
         ;;
     stop)
         if [[ ${#exists[@]} -gt 0 ]]; then
-            container="${APP_CONTAINER}$(( ${#exists[@]} - 1))"
-            docker stop "${container}"
+            docker stop "${APP_CONTAINER}${MAX_ID}"
+        fi
+        ;;
+    restart)
+        if [[ ${#exists[@]} -gt 0 ]]; then
+            ip="$(docker port "${APP_CONTAINER}${MAX_ID}" "${APP_LISTEN_PORT}")"
+            docker stop "${APP_CONTAINER}${MAX_ID}"
+            initialize_container
+            [[ -n "${ip}" ]] && export "DOCKER_OPTION_publish_port=--publish=${ip}:${APP_LISTEN_PORT}"
+
+            if cmd "${APP_CONTAINER}${MAX_ID}" "${APP_IMAGE}" -d -w "${DOCUMENT_ROOT}" --  -- "${start}"; then
+                if [[ -n "${db}" ]];then
+                    docker exec "${APP_CONTAINER}${MAX_ID}" host.sh add "dbhost" "${db}"
+                fi
+            else
+                exit 1
+            fi
         fi
         ;;
     stopall)
-        count=${#exists[@]}
-        while [[ ${count} -gt 0 ]]; do
-            container="${APP_CONTAINER}$(( --count ))"
+        for container in "${exists[@]}"; do
             docker stop "${container}"
         done
         ;;
@@ -213,38 +285,34 @@ case "$1" in
         fi
         ;;
     hostadd)
-        if [[ $# -lt 4 ]]; then
+        if [[ $# -lt 3 ]]; then
+            >&2 echo "usage: hostadd domain ip"
             exit 1
         fi
-        count=${#exists[@]}
-        start=0
-        while [[ ${start} -lt ${count} ]]; do
-            cmd "${APP_CONTAINER}${start}" "${APP_IMAGE}" host.sh add "$2" "$3"
-            ((start++))
+        for container in "${exists[@]}"; do
+            docker exec "${container}" host.sh add "$2" "$3"
         done
         ;;
     hostrm)
         if [[ $# -lt 4 ]]; then
+            >&2 echo "usage hostrm domain ip"
             exit 1
         fi
-
-        count=${#exists[@]}
-        start=0
-        while [[ ${start} -lt ${count} ]]; do
-            cmd "${APP_CONTAINER}${start}" "${APP_IMAGE}" host.sh remove "$2" "$3"
-            ((start++))
+        for container in "${exists[@]}"; do
+            docker exec "${container}" host.sh remove "$2" "$3"
         done
         ;;
     url)
-        id=${2:-0}
-        docker port "${APP_CONTAINER}${id}" "${APP_LISTEN_PORT}"
+        if [[ ${#exists[@]} -gt 0 ]]; then
+            docker port "${APP_CONTAINER}${MAX_ID}" "${APP_LISTEN_PORT}"
+        fi
         ;;
     *)
-        id=0
-        if [[ (-z "${1//[0-9]/}") && (${1} -lt ${#exists[@]}) ]]; then
-            id=${1}
-            shift
+        if [[ ${#exists[@]} -gt 0 ]]; then
+            docker exec -ti "${APP_CONTAINER}${MAX_ID}" "$@"
+        else
+            initialize_container
+            cmd "${APP_CONTAINER}${MAX_ID}" "${APP_IMAGE}" -ti -- -- "$@"
         fi
-        cmd "${APP_CONTAINER}${id}" "${APP_IMAGE}" -ti -- -ti -- "$@"
         ;;
 esac
diff --git a/Packages/server/dnsmasq/bin/dns b/Packages/server/dnsmasq/bin/dns
--- a/Packages/server/dnsmasq/bin/dns
+++ b/Packages/server/dnsmasq/bin/dns
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+set -ae
 show_help() {
     echo "Usage: $0 [options] command [args]"
     echo "Options:
@@ -14,6 +15,15 @@ Command:
     *  args                 : command to run in server
     "
 }
+
+[[ ! -f "${DIR}/dns.conf" ]] && >&2 echo "dns server configuration file not found" && exit 1
+# include default values
+source "$(dirname "$(dirname "${BASH_SOURCE[0]}")")/dns.conf"
+source "${DIR}/dns.conf"
+
+unset publishIp
+unset port
+unset move
 
 args=()
 port=53
diff --git a/Packages/server/mariadb/bin/db b/Packages/server/mariadb/bin/db
--- a/Packages/server/mariadb/bin/db
+++ b/Packages/server/mariadb/bin/db
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+set -ae
 # Application to manage database server
 # Usage: $0 start [[host-ip:]port]|stop
 #      : $0 startmaster|stopmaster
@@ -26,6 +27,19 @@ Command:
     *  args                 : command to run in server
     "
 }
+
+
+[[ ! -f "${DIR}/db.conf" ]] && >&2 echo "database server configuration file not found" && exit 1
+# include default values
+source "$(dirname "$(dirname "${BASH_SOURCE[0]}")")/db.conf"
+# include configuration values
+source "${DIR}/db.conf"
+
+unset publishIp
+unset port
+unset DB_MASTER_SERVER
+unset DB_MASTER_PORT
+unset move
 
 args=()
 while [[ $# -gt 0 ]]; do
@@ -126,12 +140,15 @@ if [[ -z "${exists}" ]]; then
             fi
         fi
 
-        mapfile -t dbs<<<"$(env | gerp '^DB_DATABASE_STATUS_')"
-        i=0
-        for db in "${dbs[@]}"; do
-            [[ -n "${db}" ]] && export "DOCKER_OPTION_db_$i=-e=REPLICATION_DB_${db#DB_DATABASE-STATUS_}"
-            ((i++))
-        done
+        if [[ -n "${DB_ENABLED_DATABASES}" ]]; then
+            for db in "${DB_ENALBED_DATABASE[@]}"; do
+                export "DOCKER_OPTION_db_${db}=-e=REPLICATION_DB_${db}=1"
+            done
+        elif [[ -n "${DB_DISABLED_DATABASES}" ]]; then
+            for db in "${DB_ENALBED_DATABASE[@]}"; do
+                export "DOCKER_OPTION_db_${db}=-e=REPLICATION_DB_${db}=0"
+            done
+        fi
         if [[ "${DB_REPLICATION_SERVER_ID}" -ge 1 ]]; then
             export DOCKER_OPTION_master="-e=MASTER_SERVER=${DB_MASTER_SERVER}"
             [[ -n "${DB_MASTER_PORT}" ]] && export DOCKER_OPTION_masterport="-e=MASTER_PORT=${DB_MASTER_PORT}"
diff --git a/Packages/server/postfix/bin/mail b/Packages/server/postfix/bin/mail
--- a/Packages/server/postfix/bin/mail
+++ b/Packages/server/postfix/bin/mail
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -ae
+
 show_help() {
     echo "Usage: $0 [Options] command [args]"
     echo "Options:
@@ -13,6 +15,11 @@ commands:
     * args                          : execute a command in server.
 "
 }
+
+[[ ! -f "${DIR}/mail.conf" ]] && >&2 echo "mail server configuration file not found" && exit 1
+# include default values
+source "$(dirname "$(dirname "${BASH_SOURCE[0]}")")/mail.conf"
+source "${DIR}/mail.conf"
 
 args=()
 port=25
