generalizing kubernet configuration generation

diff --git a/Packages/projects/webserver/bin/deploy b/Packages/projects/webserver/bin/deploy
--- a/Packages/projects/webserver/bin/deploy
+++ b/Packages/projects/webserver/bin/deploy
@@ -3,17 +3,34 @@
 set -e
 
 function show_help() {
-echo "Usage: $0 options"
+echo "Usage: $0 options
+Create kubernets yaml file from configuration values and appy delete or print yaml file.
+"
 echo "Options:
 --gcloud  [projectname] : deploy to gcloud, used for retrieving image.
 --trusted  ip           : public ip address of balancer
 --mail  ip              : mail server ip address
 --dns   ip              : dns server ip address
 --nfs   ip              : nfs server ip address
+--file conffile         : yaml or template file will search for conffile.[template.].yaml
+                           specify multiple times to concatenate multiple files.
+                           default to namespace, configMap, volume and deployment
 --print                 : do not deploy print generated configuration file.
 --delete                : delete deployment
 --help                  : show this help and exit
 "
+}
+
+function sed_command() {
+    for var in "${@:4}"; do
+        if [[ ! -v ${var} ]]; then
+            >&2 echo "undefined variable '$var' in file '$1'"
+            exit 1
+        fi
+        value="$(eval "printf '%s' \$${var}")"
+        ESCAPED_value=$(printf '%s\n' "$value" | sed -e 's/[\/&]/\\&/g')
+        replace+=(-e "s/~$2{${var}}$3~/${ESCAPED_value}/g")
+    done
 }
 
 function process_file () {
@@ -22,43 +39,21 @@ function process_file () {
     # GENERIC VARIABLES
     mapfile -t vars<<<"$(grep -o '~~{.*}~~' "$1" | sort -r | uniq |cut -d~ -f3 | cut -d{ -f2 | cut -d} -f1)"
     if [[ (${#vars[@]} -ne 1) || (-n "${vars[0]}") ]]; then
-        for var in "${vars[@]}"; do
-            eval "if [[ -z \$${var} ]]; then >&2 echo undefined variable '$var' in file '$1' && exit 1; fi"
-            value="$(eval "printf '%s' \$${var}")"
-            ESCAPED_value=$(printf '%s\n' "$value" | sed -e 's/[\/&]/\\&/g')
-            replace+=(-e "s/~~{${var}}~~/${ESCAPED_value}/g")
-        done
+        sed_command "$1" '~' '~' "${vars[@]}"
     fi
-    # APP VARIABLES
-    mapfile -t vars<<<"$(grep -o '~{app}{.*}~' "$1" | sort -r | uniq |cut -d~ -f2 | cut -d{ -f3 | cut -d} -f1)"
-    if [[ (${#vars[@]} -ne 1) || (-n "${vars[0]}") ]]; then
-        # load configuration files.
-        [[ ! -f "${DIR}/app.conf" ]] && >&2 echo "application configuration file not found" && exit 1
-        # include default values
-        source "$(dirname "$(dirname "$(/usr/bin/which app)")")/app.conf"
-        source "${DIR}/app.conf"
-        APP_IMAGE="${APP_IMAGE:+${IMAGE_PREFIX}${APP_IMAGE}}"
-        for var in "${vars[@]}"; do
-            eval "if [[ -z \$${var} ]]; then >&2 echo undefined variable '{app}$var' in file '$1' && exit 1; fi"
-            value="$(eval "printf '%s' \$${var}")"
-            ESCAPED_value=$(printf '%s\n' "$value" | sed -e 's/[\/&]/\\&/g')
-            replace+=(-e "s/~{app}{${var}}~/${ESCAPED_value}/g")
-        done
-    fi
-    # WEB VARIABLES
-    mapfile -t vars<<<"$(grep -o '~{web}{.*}~' "$1" | sort -r | uniq |cut -d~ -f2 | cut -d{ -f3 | cut -d} -f1)"
-    if [[ (${#vars[@]} -ne 1) || (-n "${vars[0]}") ]]; then
-        # load configuration files.
-        [[ ! -f "${DIR}/web.conf" ]] && >&2 echo "web configuration file not found" && exit 1
-        # include default values
-        source "$(dirname "$(dirname "$(/usr/bin/which web)")")/web.conf"
-        source "${DIR}/web.conf"
-        WEB_IMAGE="${WEB_IMAGE:+${IMAGE_PREFIX}${WEB_IMAGE}}"
-        for var in "${vars[@]}"; do
-            eval "if [[ -z \$${var} ]]; then >&2 echo undefined variable '{web}$var' in file '$1' && exit 1; fi"
-            value="$(eval "printf '%s' \$${var}")"
-            ESCAPED_value=$(printf '%s\n' "$value" | sed -e 's/[\/&]/\\&/g')
-            replace+=(-e "s/~{web}{${var}}~/${ESCAPED_value}/g")
+    mapfile -t commands<<<"$(grep -o '~{.*}{.*}~' "$1" | cut -d~ -f2 | cut -d{ -f2 | cut -d} -f1 | sort | uniq)"
+    if [[ (${#commands[@]} -ne 1) || (-n "${commands[0]}") ]]; then
+        for command in "${commands[@]}"; do
+            mapfile -t vars<<<"$(grep -o "~{${command}}{.*}~" "$1" | sort -r | uniq |cut -d~ -f2 | cut -d{ -f3 | cut -d} -f1)"
+            if [[ (${#vars[@]} -ne 1) || (-n "${vars[0]}") ]]; then
+                [[ ! -f "${DIR}/${command}.conf" ]] && >&2 echo "command:${command} configuration file not found while processing $1" && exit 1
+                # include default values
+                source "$(dirname "$(dirname "$(/usr/bin/which "${command}")")")/${command}.conf"
+                source "${DIR}/${command}.conf"
+                # for kubernets use registry prefix for image.
+                eval "${command^^}_IMAGE=\"\${${command^^}_IMAGE:+\${IMAGE_PREFIX}\${${command^^}_IMAGE}}\""
+                sed_command "$1" "{${command}}" "" "${vars[@]}"
+            fi
         done
     fi
     if [[ ${#replace[@]} -ne 0 ]]; then
@@ -68,7 +63,7 @@ function process_file () {
     fi
 }
 
-args=()
+files=()
 while [[ $# -gt 0 ]]; do
     case "$1" in
         --help)
@@ -85,18 +80,22 @@ while [[ $# -gt 0 ]]; do
             IMAGE_PREFIX="gcr.io/${PROJECT}/"
             ;;
         --trusted)
+            [[ (-z "$2") || "$2" = "--"* ]] && >&2 echo "trusted ip address needed" && exit 1
             TRUSTED_PROXY="$2"
             shift
             ;;
         --mail)
+            [[ (-z "$2") || "$2" = "--"* ]] && >&2 echo "--mail require server ip or host name" && exit 1
             MAIL_FORWARD_HOST="$2"
             shift
             ;;
         --dns)
+            [[ (-z "$2") || "$2" = "--"* ]] && >&2 echo "--dns require server ip or host name" && exit 1
             DNS_SERVER="$2"
             shift
             ;;
         --nfs)
+            [[ (-z "$2") || "$2" = "--"* ]] && >&2 echo "--nfs require network storage server ip or host name" && exit 1
             DATA_SERVER="$2"
             shift
             ;;
@@ -105,6 +104,11 @@ while [[ $# -gt 0 ]]; do
             ;;
         --delete)
             __DELETE_DEPLOYMENT=1
+            ;;
+        --file)
+            [[ (-z "$2") || "$2" = "--"* ]] && >&2 echo "--file require a template or yaml file to process" && exit 1
+            files+=("$2")
+            shift
             ;;
         *)
             >&2 echo "unknown option '$1' in commandline" && exit 1
@@ -117,13 +121,20 @@ done
 [[ -z "${DNS_SERVER}" ]] && >&2 echo "dns server not configured use --dns" && exit 1
 [[ -z "${DATA_SERVER}" ]] && >&2 echo "network data server not configured use --nfs" && exit 1
 
-files=(namespace configMap volume deployment)
+if [[ ${#files[@]} -eq 0 ]]; then
+    files=(namespace configMap volume deployment)
+fi
 source=()
+base_DIR="$(dirname "$(dirname "${BASH_SOURCE[0]}")")"
 for file in "${files[@]}"; do
     if [[ -f "${DIR}/${file}.yaml" ]]; then
         source+=("$(cat "${DIR}/${file}.yaml")")
     elif [[ -f "${DIR}/${file}.template.yaml" ]]; then
         source+=("$(process_file "${DIR}/${file}.template.yaml")")
+    # elif [[ -f "${base_DIR}/${file}.yaml" ]]; then
+    #     source+=("$(cat "${base_DIR}/${file}.yaml")")
+    elif [[ -f "${base_DIR}/${file}.template.yaml" ]]; then
+        source+=("$(process_file "${base_DIR}/${file}.template.yaml")")
     else
         >&2 echo "the file, $file.yaml or $file.template.yaml not found" && exit 1
     fi
